import { RhEmpleadoPK } from "./RhEmpleadoPK";
import { PrdSector } from "../produccion/PrdSector";
import { RhCategoria } from "./RhCategoria";
import { RhRol } from "./RhRol";
import { RhEmpleadoDescuentosFijos } from "./RhEmpleadoDescuentosFijos";
import { RhXiiiSueldo } from "./RhXiiiSueldo";
import { RhPrestamo } from "./RhPrestamo";
import { RhVacaciones } from "./RhVacaciones";
import { RhBono } from "./RhBono";
import { RhXivSueldo } from "./RhXivSueldo";
import { RhAnticipo } from "./RhAnticipo";
import { RhUtilidades } from "./RhUtilidades";
import { RhSalarioDigno } from "./RhSalarioDigno";

export class RhEmpleado {
    rhEmpleadoPK: RhEmpleadoPK = new RhEmpleadoPK();
    empTipoId: string = "";
    empResidenciaTipo: string = "";
    empResidenciaPais: string = "";
    empConvenio: string = "";
    empApellidos: string = "";
    empNombres: string = "";
    empGenero: string = "";
    empFechaNacimiento: Date = null;
    empEstadoCivil: string = "";
    empCargasFamiliares: number = 0;
    empProvincia: string = "";
    empCanton: string = "";
    empLugarNacimiento: string = "";
    empDomicilio: string = "";
    empNumero: string = "";
    empTelefono: string = "";
    empCorreoElectronico: string = "";
    empFechaPrimerIngreso: Date = null;
    empFechaPrimeraSalida: any;
    empFechaUltimoIngreso: Date = null;
    empFechaUltimaSalida: any;
    empMotivoSalida: string = null;
    empFechaAfiliacionIess: Date = null;
    empCodigoAfiliacionIess: string = "";
    empCodigoCargo: string = "";
    empCargo: string = "";
    empSueldoIess: number = 0;
    empFormaPago: string = "";
    empDiasTrabajados: number = 0;
    empDiasDescanso: number = 0;
    empBonoFijo: number = 0;
    empBonoFijoNd: number = 0;
    empOtrosIngresos: number = 0;
    empOtrosIngresosNd: number = 0;
    empExtensionCoberturaIess: boolean = false;
    empCancelarXiiiSueldoMensualmente: boolean = false;
    empCancelarXivSueldoMensualmente: boolean = false;
    empCancelarFondoReservaMensualmente: boolean = false;
    empRetencion: boolean = false;
    empEducacion: number = 0;
    empAlimentacion: number = 0;
    empSalud: number = 0;
    empVivienda: number = 0;
    empVestuario: number = 0;
    empRebajaDiscapacidad: number = 0;
    empRebajaTerceraEdad: number = 0;
    empSueldoOtraCompania: number = 0;
    empOtrasDeducciones: number = 0;
    empOtrasRebajas: number = 0;
    empUtilidades: number = 0;
    empObservaciones: string = "";
    empDiscapacidadTipo: string = "";
    empDiscapacidadPorcentaje: number = 0;
    empDiscapacidadIdTipo: string = "";
    empDiscapacidadIdNumero: string = "";
    empBanco: string = "";
    empCuentaTipo: string = "";
    empCuentaNumero: string = "";
    empSalarioNeto: boolean = false;
    empInactivo: boolean = false;
    empSaldoAnterior: number = 0;
    empSaldoAnticipos: number = 0;
    empSaldoBonos: number = 0;
    empSaldoBonosNd: number = 0;
    empSaldoPrestamos: number = 0;
    empSaldoCuotas: number = 0;
    empFechaUltimoSueldo: Date = null;
    prdSector: PrdSector = new PrdSector();
    rhCategoria: RhCategoria = new RhCategoria();
    usrEmpresa: string = "";
    usrCodigo: string = "";
    usrFechaInserta: Date = null;
    rhRolList: Array<RhRol> = null;
    rhEmpleadoDescuentosFijosList: Array<RhEmpleadoDescuentosFijos> = [];
    rhXiiiSueldoList: Array<RhXiiiSueldo> = null;
    rhPrestamoList: Array<RhPrestamo> = null;
    rhVacacionesList: Array<RhVacaciones> = null;
    rhBonoList: Array<RhBono> = null;
    rhXivSueldoList: Array<RhXivSueldo> = null;
    rhAnticipoList: Array<RhAnticipo> = null;
    rhUtilidadesList: Array<RhUtilidades> = null;
    rhSalarioDignoList: Array<RhSalarioDigno> = null;

    constructor(data?) {
        data ? this.hydrate(data) : null;
    }
    hydrate(data) {
        this.rhEmpleadoPK = data.rhEmpleadoPK ? data.rhEmpleadoPK : this.rhEmpleadoPK;
        this.empTipoId = data.empTipoId ? data.empTipoId : this.empTipoId;
        this.empResidenciaTipo = data.empResidenciaTipo ? data.empResidenciaTipo : this.empResidenciaTipo;
        this.empResidenciaPais = data.empResidenciaPais ? data.empResidenciaPais : this.empResidenciaPais;
        this.empConvenio = data.empConvenio ? data.empConvenio : this.empConvenio;
        this.empApellidos = data.empApellidos ? data.empApellidos : this.empApellidos;
        this.empNombres = data.empNombres ? data.empNombres : this.empNombres;
        this.empGenero = data.empGenero ? data.empGenero : this.empGenero;
        this.empFechaNacimiento = data.empFechaNacimiento ? data.empFechaNacimiento : this.empFechaNacimiento;
        this.empEstadoCivil = data.empEstadoCivil ? data.empEstadoCivil : this.empEstadoCivil;
        this.empCargasFamiliares = data.empCargasFamiliares ? data.empCargasFamiliares : this.empCargasFamiliares;
        this.empProvincia = data.empProvincia ? data.empProvincia : this.empProvincia;
        this.empCanton = data.empCanton ? data.empCanton : this.empCanton;
        this.empLugarNacimiento = data.empLugarNacimiento ? data.empLugarNacimiento : this.empLugarNacimiento;
        this.empDomicilio = data.empDomicilio ? data.empDomicilio : this.empDomicilio;
        this.empNumero = data.empNumero ? data.empNumero : this.empNumero;
        this.empTelefono = data.empTelefono ? data.empTelefono : this.empTelefono;
        this.empCorreoElectronico = data.empCorreoElectronico ? data.empCorreoElectronico : this.empCorreoElectronico;
        this.empFechaPrimerIngreso = data.empFechaPrimerIngreso ? data.empFechaPrimerIngreso : this.empFechaPrimerIngreso;
        this.empFechaPrimeraSalida = data.empFechaPrimeraSalida ? data.empFechaPrimeraSalida : this.empFechaPrimeraSalida;
        this.empFechaUltimoIngreso = data.empFechaUltimoIngreso ? data.empFechaUltimoIngreso : this.empFechaUltimoIngreso;
        this.empFechaUltimaSalida = data.empFechaUltimaSalida ? data.empFechaUltimaSalida : this.empFechaUltimaSalida;
        this.empMotivoSalida = data.empMotivoSalida ? data.empMotivoSalida : this.empMotivoSalida;
        this.empFechaAfiliacionIess = data.empFechaAfiliacionIess ? data.empFechaAfiliacionIess : this.empFechaAfiliacionIess;
        this.empCodigoAfiliacionIess = data.empCodigoAfiliacionIess ? data.empCodigoAfiliacionIess : this.empCodigoAfiliacionIess;
        this.empCodigoCargo = data.empCodigoCargo ? data.empCodigoCargo : this.empCodigoCargo;
        this.empCargo = data.empCargo ? data.empCargo : this.empCargo;
        this.empSueldoIess = data.empSueldoIess ? data.empSueldoIess : this.empSueldoIess;
        this.empFormaPago = data.empFormaPago ? data.empFormaPago : this.empFormaPago;
        this.empDiasTrabajados = data.empDiasTrabajados ? data.empDiasTrabajados : this.empDiasTrabajados;
        this.empDiasDescanso = data.empDiasDescanso ? data.empDiasDescanso : this.empDiasDescanso;
        this.empBonoFijo = data.empBonoFijo ? data.empBonoFijo : this.empBonoFijo;
        this.empBonoFijoNd = data.empBonoFijoNd ? data.empBonoFijoNd : this.empBonoFijoNd;
        this.empOtrosIngresos = data.empOtrosIngresos ? data.empOtrosIngresos : this.empOtrosIngresos;
        this.empOtrosIngresosNd = data.empOtrosIngresosNd ? data.empOtrosIngresosNd : this.empOtrosIngresosNd;
        this.empExtensionCoberturaIess = data.empExtensionCoberturaIess ? data.empExtensionCoberturaIess : this.empExtensionCoberturaIess;
        this.empCancelarXiiiSueldoMensualmente = data.empCancelarXiiiSueldoMensualmente ? data.empCancelarXiiiSueldoMensualmente : this.empCancelarXiiiSueldoMensualmente;
        this.empCancelarXivSueldoMensualmente = data.empCancelarXivSueldoMensualmente ? data.empCancelarXivSueldoMensualmente : this.empCancelarXivSueldoMensualmente;
        this.empCancelarFondoReservaMensualmente = data.empCancelarFondoReservaMensualmente ? data.empCancelarFondoReservaMensualmente : this.empCancelarFondoReservaMensualmente;
        this.empRetencion = data.empRetencion ? data.empRetencion : this.empRetencion;
        this.empEducacion = data.empEducacion ? data.empEducacion : this.empEducacion;
        this.empAlimentacion = data.empAlimentacion ? data.empAlimentacion : this.empAlimentacion;
        this.empSalud = data.empSalud ? data.empSalud : this.empSalud;
        this.empVivienda = data.empVivienda ? data.empVivienda : this.empVivienda;
        this.empVestuario = data.empVestuario ? data.empVestuario : this.empVestuario;
        this.empRebajaDiscapacidad = data.empRebajaDiscapacidad ? data.empRebajaDiscapacidad : this.empRebajaDiscapacidad;
        this.empRebajaTerceraEdad = data.empRebajaTerceraEdad ? data.empRebajaTerceraEdad : this.empRebajaTerceraEdad;
        this.empSueldoOtraCompania = data.empSueldoOtraCompania ? data.empSueldoOtraCompania : this.empSueldoOtraCompania;
        this.empOtrasDeducciones = data.empOtrasDeducciones ? data.empOtrasDeducciones : this.empOtrasDeducciones;
        this.empOtrasRebajas = data.empOtrasRebajas ? data.empOtrasRebajas : this.empOtrasRebajas;
        this.empUtilidades = data.empUtilidades ? data.empUtilidades : this.empUtilidades;
        this.empObservaciones = data.empObservaciones ? data.empObservaciones : this.empObservaciones;
        this.empDiscapacidadTipo = data.empDiscapacidadTipo ? data.empDiscapacidadTipo : this.empDiscapacidadTipo;
        this.empDiscapacidadPorcentaje = data.empDiscapacidadPorcentaje ? data.empDiscapacidadPorcentaje : this.empDiscapacidadPorcentaje;
        this.empDiscapacidadIdTipo = data.empDiscapacidadIdTipo ? data.empDiscapacidadIdTipo : this.empDiscapacidadIdTipo;
        this.empDiscapacidadIdNumero = data.empDiscapacidadIdNumero ? data.empDiscapacidadIdNumero : this.empDiscapacidadIdNumero;
        this.empBanco = data.empBanco ? data.empBanco : this.empBanco;
        this.empCuentaTipo = data.empCuentaTipo ? data.empCuentaTipo : this.empCuentaTipo;
        this.empCuentaNumero = data.empCuentaNumero ? data.empCuentaNumero : this.empCuentaNumero;
        this.empSalarioNeto = data.empSalarioNeto ? data.empSalarioNeto : this.empSalarioNeto;
        this.empInactivo = data.empInactivo ? data.empInactivo : this.empInactivo;
        this.empSaldoAnterior = data.empSaldoAnterior ? data.empSaldoAnterior : this.empSaldoAnterior;
        this.empSaldoAnticipos = data.empSaldoAnticipos ? data.empSaldoAnticipos : this.empSaldoAnticipos;
        this.empSaldoBonos = data.empSaldoBonos ? data.empSaldoBonos : this.empSaldoBonos;
        this.empSaldoBonosNd = data.empSaldoBonosNd ? data.empSaldoBonosNd : this.empSaldoBonosNd;
        this.empSaldoPrestamos = data.empSaldoPrestamos ? data.empSaldoPrestamos : this.empSaldoPrestamos;
        this.empSaldoCuotas = data.empSaldoCuotas ? data.empSaldoCuotas : this.empSaldoCuotas;
        this.empFechaUltimoSueldo = data.empFechaUltimoSueldo ? data.empFechaUltimoSueldo : this.empFechaUltimoSueldo;
        this.prdSector = data.prdSector ? data.prdSector : this.prdSector;
        this.rhCategoria = data.rhCategoria ? data.rhCategoria : this.rhCategoria;
        this.usrEmpresa = data.usrEmpresa ? data.usrEmpresa : this.usrEmpresa;
        this.usrCodigo = data.usrCodigo ? data.usrCodigo : this.usrCodigo;
        this.usrFechaInserta = data.usrFechaInserta ? data.usrFechaInserta : this.usrFechaInserta;
        this.rhRolList = data.rhRolList ? data.rhRolList : this.rhRolList;
        this.rhEmpleadoDescuentosFijosList = data.rhEmpleadoDescuentosFijosList ? data.rhEmpleadoDescuentosFijosList : this.rhEmpleadoDescuentosFijosList;
        this.rhXiiiSueldoList = data.rhXiiiSueldoList ? data.rhXiiiSueldoList : this.rhXiiiSueldoList;
        this.rhPrestamoList = data.rhPrestamoList ? data.rhPrestamoList : this.rhPrestamoList;
        this.rhVacacionesList = data.rhVacacionesList ? data.rhVacacionesList : this.rhVacacionesList;
        this.rhBonoList = data.rhBonoList ? data.rhBonoList : this.rhBonoList;
        this.rhXivSueldoList = data.rhXivSueldoList ? data.rhXivSueldoList : this.rhXivSueldoList;
        this.rhAnticipoList = data.rhAnticipoList ? data.rhAnticipoList : this.rhAnticipoList;
        this.rhUtilidadesList = data.rhUtilidadesList ? data.rhUtilidadesList : this.rhUtilidadesList;
        this.rhSalarioDignoList = data.rhSalarioDignoList ? data.rhSalarioDignoList : this.rhSalarioDignoList;

    }
}